### ISSUE TITLE
MAP  사용 해 보고 정리해보았습니다. 

### ISSUE THREAD

**Issue by pkogokhj** [abmi-admin/OMOP-Standard-Vocabulary#1]
김효정 연구원입니다. 
1. 검색 속도 등 반응속도가 너무 느림
2. 주어진 갯수만큼 번호가 추가되었으면 좋겠음. - 임시저장 갯수/ 전체 할당 갯 수
3. 검색결과 나오는 부분 글씨를 작게하더라도 더 많이 보였으면 좋겠음. 현재는 2개 보이는데 4개이상 보였음 좋겠음.
4. 현재는 더블클릭시 클릭한 박스 부분만 복사 되는데 블럭지정 복사가 되었음 좋겠음. 
5. 원클릭시 검색이 되니 클 릭 후 맵핑대상없음 누르고 싶은데 검색된다는 메세지 나오는 창이 나와 불편함.
 그래서 더블클릭하면 검색되면 좋겠음.-클릭만 하면 검색이 되니 의도치 않게 클릭을 하게되면   검색이 되면서 속도가 더 느려지는 거 같음. 
6. 아랫쪽 검색창 검색결과를  target concept id로 넣고 아랫쪽이 같은 약인경우 그대로 다시 넣고 싶은데 임시저장을 하고 나면 검색결과 자체가 없으져서 같은약을 두번 검색해야 하는 번거로움이 있음.
7. 아랫쪽 검색창 concept name 에 성분명 검색하면 안나오는 경우가 많음- Usagi내에서 검색가능함.
8. comment 쓰고 나서 수정이 안되고 추가만 되는 거 같음 - 수정 , 추가 , 삭제 기능 필요함. 
9. 아랫쪽 검색창에 약성분을 두개이상 입력하거나 ' Irinotecan hcl 100 MG  Injective Injection'이렇게 여러가지 정보를 넣어도 검색이 안됨.

**Comment by sumannam** [comment]
2018-03-15 내용 정리 완료
