### ISSUE TITLE
[MAP] 결과 내 검색 모두선택/모두해제 기능 추가

### ISSUE THREAD

**Issue by sumannam** [abmi-admin/OMOP-Standard-Vocabulary#11]
우측의 '결과내 검색을 위한 검색어 입력'란이 V 체크가 다 되어있는데 전체클릭해서 선택/해제할수 있는 칸이 있으면 좋겠습니다. 그리고 기본으로 clinical drug 만 체크가 되있던지 하고, 다음 코드로 넘어가도 초기화되지 않았으면 좋겠습니다. - 지금은 다 V 되어있어 광범위하게 검색되어 더 느린것 같음.

From 어소영연구원

**Comment by Nebu1eto** [comment]
Accept
