### ISSUE TITLE
MAP 건의내용입니다

### ISSUE THREAD

**Issue by afnasy** [abmi-admin/OMOP-Standard-Vocabulary#2]
어소영 매핑 연구원입니다.
오늘 프로그램 사용 후 건의드릴 것 적어보았습니다.
수고하세요~

=================================================================
* 우측의 '결과내 검색을 위한 검색어 입력'란이 V 체크가 다 되어있는데 전체클릭해서 선택/해제할수 있는 칸이 있으면 좋겠습니다. 그리고 기본으로 clinical drug 만 체크가 되있던지 하고, 다음 코드로 넘어가도 초기화되지 않았으면 좋겠습니다. - 지금은 다 V 되어있어 광범위하게 검색되어 더 느린것 같음.

* 매핑했던 결과를 다시 확인하고 싶은데 지금은 확인이 어렵습니다. 매핑 한 ID를 클릭하거나 커서 올렸을 때 매핑결과가 box로 뜨던지 해서 확인가능하면 좋겠습니다

* 더블클릭 할 때 전체셀 복사가 되는데 단어 일부만 복사되면 좋겠습니다.

* 코멘트 수정 or 삭제 기능.

* 연구원 개인이 자신의 업무 진행정도를 확인할 수 있으면 좋겠습니다.(코드 숫자 확인)

* 맨 밑 검색창 검색이 잘 안되거나 불필요한 코드까지 검색됨, 단어 2개 입력시 검색안됨.

* 전체 창 크기 및 글씨크기 변경, 안되면 candidate list 라도 더 많이 보이게 늘려주세요
===========================================================

**Comment by sumannam** [comment]
2018-03-15 내용 정리 완료
