### ISSUE TITLE
[MAP] 후보군과 Concept 결과 내용 늘리기

### ISSUE THREAD

**Issue by sumannam** [abmi-admin/OMOP-Standard-Vocabulary#5]
Usagi처럼 글씨가 작게해서 후보와 cocenpt 겨로가 내용 더 보여주기

From 김효정연구원
From 어소영연구원

**Comment by Nebu1eto** [comment]
Policy: 글자 크기를 유동적으로 늘릴 수 있도록 관리하도록 개발.
Accept
